name: api integration testing

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:


            - name: checkout code
              uses: actions/checkout@v3


            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  push: true
                  tags: cloudymax76/integration-assi_task4:latest
                #   secrets: |
                #     GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}

            - name: Run Docker Container
              run: docker run -d -p 5000:5000 cloudymax76/integration-assi_task4:latest


            - name: Install node.js
              uses: actions/setup-node@v3
              with:
                node-version: 16

            - name: install newman
              run: npm install -g newman
    
            - name: Wait for API to Start
              run: sleep 15
 
            - name: Run Postman Test 
              run: newman run response.json
